[package]
name = "optimized_nn"
version = "0.1.0"
authors = ["Oskar Nehlin <o-nehlin@hotmail.com>"]

[profile.release]
opt-level = 3
codegen-units=1
lto = "fat"

[dependencies]
ndarray = "0.11.2"
rand = "0.5"
image = "0.19.0"
