[package]
name = "rust_nn"
version = "0.1.0"
authors = ["Oskar Nehlin <o-nehlin@hotmail.com>"]

[dependencies]
rand = "0.5"
image = "0.19.0"

[dev-dependencies]
criterion = "0.2"

[[bench]]
name = "my_benchmark"
harness = false

